### ISSUE TITLE
failed to start in the Cytoscape

### ISSUE THREAD

**Issue by diablosky** [cas-bioinf/genexpi#1]
I install the plugin in app store in Cytoscape, but no matter how many times I uninstall and reinstall it , it said "Failed to Start" in my Cytoscape.

**Comment by martinmodrak** [comment]
Sorry you are having trouble - could you please provide me with more details to help me troubleshoot the issue? What OS are you under and which Cytoscape version are you using?

Could you please also post console output from running Cytoscape via cystoscape.bat (Windows) or from a  terminal via cytoscape.sh (Linux). Thanks!

**Comment by MLKaufman** [comment]
Having the same issue on both Mac and PC. Cytoscape cannot load the module.

**Comment by martinmodrak** [comment]
Thanks for reporting and sorry you are having trouble. I finally got a fresh computer that manifested the error and the problem was that Cytoscape downloaded a wrong version of a dependency. Nevertheless, I should've caught that earlier. I released a new version of both CyGenexpi and the dependency (CyDataSeries) and Cytoscape now correctly recognizes what the latest version of CyDataSeries is. Please try updating/reinstalling CyGenexpi, it should resolve the problem.

**Comment by martinmodrak** [comment]
The problem is tracked at Cytoscape as http://code.cytoscape.org/redmine/issues/4181

**Comment by MLKaufman** [comment]
Thanks! Working now. Congrats on the publication!
